name: "deploy-shiny"
on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 4,14 * * *"
  push:
   branches:
    - main
   paths:
    - nowcast_viz_de/plot_data/** # trigger when updated by prepare-plot-data
   

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
          r-version: 4.1.0
        
    - name: Push to shiny.io
      env:
        SHINYAPPS_NAME: ${{secrets.SHINYAPPS_NAME}}
        SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
        SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}
      
      run: |
        Rscript ./code/deploy_shiny.R
