name: "fetch-nowcasts"
on:
  workflow_dispatch:
  

jobs:
  fetch-nowcasts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # otherwise, you will failed to push refs to dest repo
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v1  
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        
    - name: Install dependencies
      run: python3 -m pip install pandas
      
#     - run: false

    - name: Fetch RKI
      run: python3 ./code/fetch_nowcasts/fetch-RKI.py	
      if: always()  
      
    - name: Fetch SZ
      run: python3 ./code/fetch_nowcasts/fetch-SZ.py	
      if: always()  
    
    - name: Fetch epiforecasts
      run: Rscript ./code/fetch_nowcasts/epiforecasts_url2nowcast.R	
      if: always()
      
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Fetch Nowcasts"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/hospitalization-nowcast-hub.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit --allow-empty -m "Daily nowcast update"
      if: always()
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
      if: always()
