name: "run-baseline"
on:
  workflow_dispatch:
  
jobs:
  fetch-nowcasts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
#       with:
#         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
#         fetch-depth: 1 # otherwise, you will failed to push refs to dest repo
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v1  
      
    - name: Run baseline
      run: Rscript ./code/baseline/run_baseline.R
    
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Run Baseline"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/hospitalization-nowcast-hub.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit --allow-empty -m "Daily baseline update"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
